# Bienvenido a Jekyll!
#
# Este archivo de configuración es para ajustes que afectan a todo tu blog, valores
# que se espera configurar una vez y editar raramente después de eso. Si te encuentras
# editando este archivo muy a menudo, considera usar la función de archivos de datos de Jekyll
# para los datos que necesitas actualizar con frecuencia.
#
# Por razones técnicas, este archivo *NO* se recarga automáticamente cuando usas
# 'bundle exec jekyll serve'. Si cambias este archivo, por favor reinicia el proceso del servidor.

# Configuraciones del sitio
# Estas se utilizan para personalizar tu nuevo sitio. Si miras en los archivos HTML,
# verás que se accede a ellos a través de {{ site.title }}, {{ site.email }}, y así sucesivamente.
# Puedes crear cualquier variable personalizada que desees, y estarán accesibles
# en las plantillas a través de {{ site.myvariable }}.
title: Application of Convolutional Neural Networks to Time-Domain Astrophysics: 2D Image Analysis of OGLE (Phase-Folded) Light Curves
email: tu-email@example.com
description: >-
  Este sitio presenta la investigación de Monsalves Gonzalez, N. en la aplicación de Redes Neuronales Convolucionales al análisis de curvas de luz plegadas de fase del proyecto OGLE en astrofísica de dominio temporal. Explora innovadores enfoques de análisis de imágenes 2D.
baseurl: "" # el subpath de tu sitio, ej. /blog
url: "" # el hostname base & protocolo para tu sitio, ej. http://tusitio.com
twitter_username: tu_usuario_twitter
github_username:  tu_usuario_github

# Configuraciones de compilación
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Excluir del procesamiento.
# Los siguientes elementos no serán procesados, por defecto. Crea una lista personalizada
# para sobrescribir la configuración por defecto.
# exclude:

